// AUTO-GENERATED by `npm run build:widget` in agent/ — edit agent/widget/chat-widget.js instead.
"use strict";
(() => {
  // node_modules/agents/dist/utils.js
  var INTERNAL_JS_STUB_PROPS = /* @__PURE__ */ new Set([
    "toJSON",
    "then",
    "catch",
    "finally",
    "valueOf",
    "toString",
    "constructor",
    "prototype",
    "$$typeof",
    "@@toStringTag",
    "asymmetricMatch",
    "nodeType"
  ]);
  function isInternalJsStubProp(prop) {
    return typeof prop === "symbol" || INTERNAL_JS_STUB_PROPS.has(prop);
  }
  function camelCaseToKebabCase(str) {
    if (str === str.toUpperCase() && str !== str.toLowerCase()) return str.toLowerCase().replace(/_/g, "-");
    let kebabified = str.replace(/[A-Z]/g, (letter) => `-${letter.toLowerCase()}`);
    kebabified = kebabified.startsWith("-") ? kebabified.slice(1) : kebabified;
    return kebabified.replace(/_/g, "-").replace(/-$/, "");
  }

  // node_modules/partysocket/dist/ws.js
  if (!globalThis.EventTarget || !globalThis.Event)
    console.error(`
  PartySocket requires a global 'EventTarget' class to be available!
  You can polyfill this global by adding this to your code before any partysocket imports: 
  
  \`\`\`
  import 'partysocket/event-target-polyfill';
  \`\`\`
  Please file an issue at https://github.com/partykit/partykit if you're still having trouble.
`);
  var ErrorEvent = class extends Event {
    message;
    error;
    constructor(error, target) {
      super("error", target);
      this.message = error.message;
      this.error = error;
    }
  };
  var CloseEvent = class extends Event {
    code;
    reason;
    wasClean = true;
    constructor(code = 1e3, reason = "", target) {
      super("close", target);
      this.code = code;
      this.reason = reason;
    }
  };
  var Events = {
    Event,
    ErrorEvent,
    CloseEvent
  };
  function assert(condition, msg) {
    if (!condition) throw new Error(msg);
  }
  function cloneEventBrowser(e) {
    return new e.constructor(e.type, e);
  }
  function cloneEventNode(e) {
    if ("data" in e) return new MessageEvent(e.type, e);
    if ("code" in e || "reason" in e)
      return new CloseEvent(e.code || 1999, e.reason || "unknown reason", e);
    if ("error" in e) return new ErrorEvent(e.error, e);
    return new Event(e.type, e);
  }
  var isNode = typeof process !== "undefined" && typeof process.versions?.node !== "undefined";
  var isReactNative = typeof navigator !== "undefined" && navigator.product === "ReactNative";
  var cloneEvent = isNode || isReactNative ? cloneEventNode : cloneEventBrowser;
  var DEFAULT = {
    maxReconnectionDelay: 1e4,
    minReconnectionDelay: 3e3,
    minUptime: 5e3,
    reconnectionDelayGrowFactor: 1.3,
    connectionTimeout: 4e3,
    maxRetries: Number.POSITIVE_INFINITY,
    maxEnqueuedMessages: Number.POSITIVE_INFINITY,
    startClosed: false,
    debug: false
  };
  var didWarnAboutMissingWebSocket = false;
  function absorbError() {
  }
  var ReconnectingWebSocket = class ReconnectingWebSocket2 extends EventTarget {
    _ws;
    _retryCount = -1;
    _uptimeTimeout;
    _connectTimeout;
    _shouldReconnect = true;
    _connectLock = false;
    _binaryType = "blob";
    _closeCalled = false;
    _didWarnAboutClosedSend = false;
    _messageQueue = [];
    _debugLogger = console.log.bind(console);
    _url;
    _protocols;
    _options;
    constructor(url, protocols, options = {}) {
      super();
      this._url = url;
      this._protocols = protocols;
      this._options = options;
      if (this._options.startClosed) this._shouldReconnect = false;
      if (this._options.debugLogger)
        this._debugLogger = this._options.debugLogger;
      this._connect();
    }
    static get CONNECTING() {
      return 0;
    }
    static get OPEN() {
      return 1;
    }
    static get CLOSING() {
      return 2;
    }
    static get CLOSED() {
      return 3;
    }
    get CONNECTING() {
      return ReconnectingWebSocket2.CONNECTING;
    }
    get OPEN() {
      return ReconnectingWebSocket2.OPEN;
    }
    get CLOSING() {
      return ReconnectingWebSocket2.CLOSING;
    }
    get CLOSED() {
      return ReconnectingWebSocket2.CLOSED;
    }
    get binaryType() {
      return this._ws ? this._ws.binaryType : this._binaryType;
    }
    set binaryType(value) {
      this._binaryType = value;
      if (this._ws) this._ws.binaryType = value;
    }
    /**
     * Returns the number or connection retries
     */
    get retryCount() {
      return Math.max(this._retryCount, 0);
    }
    /**
     * The number of bytes of data that have been queued using calls to send() but not yet
     * transmitted to the network. This value resets to zero once all queued data has been sent.
     * This value does not reset to zero when the connection is closed; if you keep calling send(),
     * this will continue to climb. Read only
     */
    get bufferedAmount() {
      return this._messageQueue.reduce((acc, message) => {
        if (typeof message === "string") acc += message.length;
        else if (message instanceof Blob) acc += message.size;
        else acc += message.byteLength;
        return acc;
      }, 0) + (this._ws ? this._ws.bufferedAmount : 0);
    }
    /**
     * The extensions selected by the server. This is currently only the empty string or a list of
     * extensions as negotiated by the connection
     */
    get extensions() {
      return this._ws ? this._ws.extensions : "";
    }
    /**
     * A string indicating the name of the sub-protocol the server selected;
     * this will be one of the strings specified in the protocols parameter when creating the
     * WebSocket object
     */
    get protocol() {
      return this._ws ? this._ws.protocol : "";
    }
    /**
     * The current state of the connection; this is one of the Ready state constants
     */
    get readyState() {
      if (this._closeCalled) return ReconnectingWebSocket2.CLOSED;
      if (this._ws) return this._ws.readyState;
      return this._options.startClosed ? ReconnectingWebSocket2.CLOSED : ReconnectingWebSocket2.CONNECTING;
    }
    /**
     * The URL as resolved by the constructor
     */
    get url() {
      return this._ws ? this._ws.url : "";
    }
    /**
     * Whether the websocket object is now in reconnectable state
     */
    get shouldReconnect() {
      return this._shouldReconnect;
    }
    /**
     * An event listener to be called when the WebSocket connection's readyState changes to CLOSED
     */
    onclose = null;
    /**
     * An event listener to be called when an error occurs
     */
    onerror = null;
    /**
     * An event listener to be called when a message is received from the server
     */
    onmessage = null;
    /**
     * An event listener to be called when the WebSocket connection's readyState changes to OPEN;
     * this indicates that the connection is ready to send and receive data
     */
    onopen = null;
    /**
     * Closes the WebSocket connection or connection attempt, if any. If the connection is already
     * CLOSED or CLOSING, this method does nothing.
     *
     * The `close` event is dispatched synchronously (mirroring how
     * `reconnect()` dispatches its synthetic close). This guarantees
     * consumers observe a terminal event for every explicit close, even
     * if their listeners are detached right after this call — previously
     * the real (asynchronous) browser close event could fire after
     * listeners were removed and go unobserved entirely.
     */
    close(code = 1e3, reason) {
      this._closeCalled = true;
      this._shouldReconnect = false;
      this._clearTimeouts();
      if (!this._ws) {
        this._debug("close enqueued: no ws instance");
        return;
      }
      if (this._ws.readyState === this.CLOSED || this._ws.readyState === this.CLOSING) {
        this._debug("close: already closing or closed");
        return;
      }
      this._disconnect(code, reason);
    }
    /**
     * Closes the WebSocket connection or connection attempt and connects again.
     * Resets retry counter;
     */
    reconnect(code, reason) {
      this._shouldReconnect = true;
      this._closeCalled = false;
      this._didWarnAboutClosedSend = false;
      this._retryCount = -1;
      if (!this._ws || this._ws.readyState === this.CLOSED || this._ws.readyState === this.CLOSING)
        this._connect();
      else {
        this._disconnect(code, reason);
        this._connect();
      }
    }
    /**
     * Enqueue specified data to be transmitted to the server over the WebSocket connection.
     *
     * @returns `true` if the message was transmitted immediately over an open
     * connection; `false` if it was buffered (sent when the connection next
     * opens — the buffer is always flushed before the `open` event is
     * dispatched) or dropped because `maxEnqueuedMessages` was reached.
     */
    send(data) {
      if (this._ws && this._ws.readyState === this.OPEN) {
        this._debug("send", data);
        this._ws.send(data);
        return true;
      }
      if (this._closeCalled && !this._didWarnAboutClosedSend) {
        this._didWarnAboutClosedSend = true;
        console.warn(
          "ReconnectingWebSocket: send() was called after close(). The message has been buffered, but it will only be delivered if reconnect() is called on this socket. If this socket has been discarded, the message is lost \u2014 this usually means a stale socket reference is being used."
        );
      }
      const { maxEnqueuedMessages = DEFAULT.maxEnqueuedMessages } = this._options;
      if (this._messageQueue.length < maxEnqueuedMessages) {
        this._debug("enqueue", data);
        this._messageQueue.push(data);
      }
      return false;
    }
    /**
     * Removes and returns all messages that were passed to send() but never
     * transmitted (they were buffered while the connection wasn't open).
     *
     * Useful when a socket is being discarded and replaced (e.g. the React
     * hooks recreate the socket when connection options change): the
     * replacement socket can re-send these messages, instead of them being
     * silently lost with the old instance.
     */
    drainQueuedMessages() {
      const queue = this._messageQueue;
      this._messageQueue = [];
      return queue;
    }
    _debug(...args) {
      if (this._options.debug) this._debugLogger("RWS>", ...args);
    }
    _getNextDelay() {
      const {
        reconnectionDelayGrowFactor = DEFAULT.reconnectionDelayGrowFactor,
        minReconnectionDelay = DEFAULT.minReconnectionDelay,
        maxReconnectionDelay = DEFAULT.maxReconnectionDelay
      } = this._options;
      let delay = 0;
      if (this._retryCount > 0) {
        delay = minReconnectionDelay * reconnectionDelayGrowFactor ** (this._retryCount - 1);
        if (delay > maxReconnectionDelay) delay = maxReconnectionDelay;
      }
      this._debug("next delay", delay);
      return delay;
    }
    _wait() {
      return new Promise((resolve) => {
        setTimeout(resolve, this._getNextDelay());
      });
    }
    _getNextProtocols(protocolsProvider) {
      if (!protocolsProvider) return Promise.resolve(null);
      if (typeof protocolsProvider === "string" || Array.isArray(protocolsProvider))
        return Promise.resolve(protocolsProvider);
      if (typeof protocolsProvider === "function") {
        const protocols = protocolsProvider();
        if (!protocols) return Promise.resolve(null);
        if (typeof protocols === "string" || Array.isArray(protocols))
          return Promise.resolve(protocols);
        if (protocols.then) return protocols;
      }
      throw Error("Invalid protocols");
    }
    _getNextUrl(urlProvider) {
      if (typeof urlProvider === "string") return Promise.resolve(urlProvider);
      if (typeof urlProvider === "function") {
        const url = urlProvider();
        if (typeof url === "string") return Promise.resolve(url);
        if (url.then) return url;
      }
      throw Error("Invalid URL");
    }
    _connect() {
      if (this._connectLock || !this._shouldReconnect) return;
      this._connectLock = true;
      const {
        maxRetries = DEFAULT.maxRetries,
        connectionTimeout = DEFAULT.connectionTimeout
      } = this._options;
      if (this._retryCount >= maxRetries) {
        this._debug("max retries reached", this._retryCount, ">=", maxRetries);
        this._connectLock = false;
        return;
      }
      this._retryCount++;
      this._debug("connect", this._retryCount);
      this._removeListeners();
      this._wait().then(
        () => Promise.all([
          this._getNextUrl(this._url),
          this._getNextProtocols(this._protocols || null)
        ])
      ).then(([url, protocols]) => {
        if (this._closeCalled) {
          this._connectLock = false;
          return;
        }
        if (!this._options.WebSocket && typeof WebSocket === "undefined" && !didWarnAboutMissingWebSocket) {
          console.error(`\u203C\uFE0F No WebSocket implementation available. You should define options.WebSocket. 

For example, if you're using node.js, run \`npm install ws\`, and then in your code:

import PartySocket from 'partysocket';
import WS from 'ws';

const partysocket = new PartySocket({
  host: "127.0.0.1:1999",
  room: "test-room",
  WebSocket: WS
});

`);
          didWarnAboutMissingWebSocket = true;
        }
        const WS = this._options.WebSocket || WebSocket;
        this._debug("connect", {
          url,
          protocols
        });
        this._ws = protocols ? new WS(url, protocols) : new WS(url);
        this._ws.binaryType = this._binaryType;
        this._connectLock = false;
        this._addListeners();
        this._connectTimeout = setTimeout(
          () => this._handleTimeout(),
          connectionTimeout
        );
      }).catch((err) => {
        this._connectLock = false;
        this._handleError(new Events.ErrorEvent(Error(err.message), this));
      });
    }
    _handleTimeout() {
      this._debug("timeout event");
      this._handleError(new Events.ErrorEvent(Error("TIMEOUT"), this));
    }
    _disconnect(code = 1e3, reason) {
      this._clearTimeouts();
      if (!this._ws) return;
      this._removeListeners();
      try {
        if (this._ws.readyState === this.OPEN || this._ws.readyState === this.CONNECTING)
          this._ws.close(code, reason);
        this._handleClose(new Events.CloseEvent(code, reason, this));
      } catch (_error) {
      }
    }
    _acceptOpen() {
      this._debug("accept open");
      this._retryCount = 0;
    }
    _handleOpen = (event) => {
      this._debug("open event");
      const { minUptime = DEFAULT.minUptime } = this._options;
      clearTimeout(this._connectTimeout);
      this._uptimeTimeout = setTimeout(() => this._acceptOpen(), minUptime);
      assert(this._ws, "WebSocket is not defined");
      this._ws.binaryType = this._binaryType;
      this._messageQueue.forEach((message) => {
        this._ws?.send(message);
      });
      this._messageQueue = [];
      if (this.onopen) this.onopen(event);
      this.dispatchEvent(cloneEvent(event));
    };
    _handleMessage = (event) => {
      this._debug("message event");
      if (this.onmessage) this.onmessage(event);
      this.dispatchEvent(cloneEvent(event));
    };
    _handleError = (event) => {
      this._debug("error event", event.message);
      this._disconnect(void 0, event.message === "TIMEOUT" ? "timeout" : void 0);
      if (this.onerror) this.onerror(event);
      this._debug("exec error listeners");
      this.dispatchEvent(cloneEvent(event));
      this._connect();
    };
    _handleClose = (event) => {
      this._debug("close event");
      this._clearTimeouts();
      if (this._options.shouldReconnectOnClose && !this._options.shouldReconnectOnClose(event))
        this._shouldReconnect = false;
      if (this._shouldReconnect) this._connect();
      if (this.onclose) this.onclose(event);
      this.dispatchEvent(cloneEvent(event));
    };
    _removeListeners() {
      if (!this._ws) return;
      this._debug("removeListeners");
      this._ws.removeEventListener("open", this._handleOpen);
      this._ws.removeEventListener("close", this._handleClose);
      this._ws.removeEventListener("message", this._handleMessage);
      this._ws.removeEventListener("error", this._handleError);
      this._ws.addEventListener("error", absorbError);
    }
    _addListeners() {
      if (!this._ws) return;
      this._debug("addListeners");
      this._ws.addEventListener("open", this._handleOpen);
      this._ws.addEventListener("close", this._handleClose);
      this._ws.addEventListener("message", this._handleMessage);
      this._ws.addEventListener("error", this._handleError);
    }
    _clearTimeouts() {
      clearTimeout(this._connectTimeout);
      clearTimeout(this._uptimeTimeout);
    }
  };

  // node_modules/partysocket/dist/index.js
  var valueIsNotNil = (keyValuePair) => keyValuePair[1] !== null && keyValuePair[1] !== void 0;
  function generateUUID() {
    if (crypto?.randomUUID) return crypto.randomUUID();
    let d = Date.now();
    let d2 = performance?.now && performance.now() * 1e3 || 0;
    return "xxxxxxxx-xxxx-4xxx-yxxx-xxxxxxxxxxxx".replace(/[xy]/g, function(c) {
      let r = Math.random() * 16;
      if (d > 0) {
        r = (d + r) % 16 | 0;
        d = Math.floor(d / 16);
      } else {
        r = (d2 + r) % 16 | 0;
        d2 = Math.floor(d2 / 16);
      }
      return (c === "x" ? r : r & 3 | 8).toString(16);
    });
  }
  function getPartyInfo(partySocketOptions, defaultProtocol, defaultParams = {}) {
    const {
      host: rawHost,
      path: rawPath,
      protocol: rawProtocol,
      room,
      party,
      basePath,
      prefix,
      query
    } = partySocketOptions;
    let host2 = rawHost.replace(/^(http|https|ws|wss):\/\//, "");
    if (host2.endsWith("/")) host2 = host2.slice(0, -1);
    if (rawPath?.startsWith("/"))
      throw new Error("path must not start with a slash");
    const name = party ?? "main";
    const path = rawPath ? `/${rawPath}` : "";
    const protocol = rawProtocol || (host2.startsWith("localhost:") || host2.startsWith("127.0.0.1:") || host2.startsWith("192.168.") || host2.startsWith("10.") || host2.startsWith("172.") && host2.split(".")[1] >= "16" && host2.split(".")[1] <= "31" || host2.startsWith("[::ffff:7f00:1]:") ? defaultProtocol : `${defaultProtocol}s`);
    const baseUrl = `${protocol}://${host2}/${basePath || `${prefix || "parties"}/${name}/${room}`}${path}`;
    const makeUrl = (query2 = {}) => `${baseUrl}?${new URLSearchParams([...Object.entries(defaultParams), ...Object.entries(query2).filter(valueIsNotNil)])}`;
    const urlProvider = typeof query === "function" ? async () => makeUrl(await query()) : makeUrl(query);
    return {
      host: host2,
      path,
      room,
      name,
      protocol,
      partyUrl: baseUrl,
      urlProvider
    };
  }
  var PartySocket = class extends ReconnectingWebSocket {
    _pk;
    _pkurl;
    name;
    room;
    host;
    path;
    basePath;
    constructor(partySocketOptions) {
      const wsOptions = getWSOptions(partySocketOptions);
      super(wsOptions.urlProvider, wsOptions.protocols, wsOptions.socketOptions);
      this.partySocketOptions = partySocketOptions;
      this.setWSProperties(wsOptions);
      if (!partySocketOptions.startClosed && !this.room && !this.basePath) {
        this.close();
        throw new Error(
          "Either room or basePath must be provided to connect. Use startClosed: true to create a socket and set them via updateProperties before calling reconnect()."
        );
      }
      if (!partySocketOptions.disableNameValidation) {
        if (partySocketOptions.party?.includes("/"))
          console.warn(
            `PartySocket: party name "${partySocketOptions.party}" contains forward slash which may cause routing issues. Consider using a name without forward slashes or set disableNameValidation: true to bypass this warning.`
          );
        if (partySocketOptions.room?.includes("/"))
          console.warn(
            `PartySocket: room name "${partySocketOptions.room}" contains forward slash which may cause routing issues. Consider using a name without forward slashes or set disableNameValidation: true to bypass this warning.`
          );
      }
    }
    updateProperties(partySocketOptions) {
      const wsOptions = getWSOptions({
        ...this.partySocketOptions,
        ...partySocketOptions,
        host: partySocketOptions.host ?? this.host,
        room: partySocketOptions.room ?? this.room,
        path: partySocketOptions.path ?? this.path,
        basePath: partySocketOptions.basePath ?? this.basePath
      });
      this._url = wsOptions.urlProvider;
      this._protocols = wsOptions.protocols;
      this._options = wsOptions.socketOptions;
      this.setWSProperties(wsOptions);
    }
    setWSProperties(wsOptions) {
      const { _pk, _pkurl, name, room, host: host2, path, basePath } = wsOptions;
      this._pk = _pk;
      this._pkurl = _pkurl;
      this.name = name;
      this.room = room;
      this.host = host2;
      this.path = path;
      this.basePath = basePath;
    }
    reconnect(code, reason) {
      if (!this.host)
        throw new Error(
          "The host must be set before connecting, use `updateProperties` method to set it or pass it to the constructor."
        );
      if (!this.room && !this.basePath)
        throw new Error(
          "The room (or basePath) must be set before connecting, use `updateProperties` method to set it or pass it to the constructor."
        );
      super.reconnect(code, reason);
    }
    get id() {
      return this._pk;
    }
    /**
     * Exposes the static PartyKit room URL without applying query parameters.
     * To access the currently connected WebSocket url, use PartySocket#url.
     */
    get roomUrl() {
      return this._pkurl;
    }
    static async fetch(options, init) {
      const party = getPartyInfo(options, "http");
      const url = typeof party.urlProvider === "string" ? party.urlProvider : await party.urlProvider();
      return (options.fetch ?? fetch)(url, init);
    }
  };
  function getWSOptions(partySocketOptions) {
    const {
      id,
      host: _host,
      path: _path,
      party: _party,
      room: _room,
      protocol: _protocol,
      query: _query,
      protocols,
      ...socketOptions
    } = partySocketOptions;
    const _pk = id || generateUUID();
    const party = getPartyInfo(partySocketOptions, "ws", { _pk });
    return {
      _pk,
      _pkurl: party.partyUrl,
      name: party.name,
      room: party.room,
      host: party.host,
      path: party.path,
      basePath: partySocketOptions.basePath,
      protocols,
      socketOptions,
      urlProvider: party.urlProvider
    };
  }

  // node_modules/agents/dist/client.js
  var AgentConnectionError = class extends Error {
    constructor(event) {
      const reason = event.reason || `WebSocket closed with code ${event.code}`;
      super(`Agent connection closed: ${reason}`);
      this.name = "AgentConnectionError";
      this.code = event.code;
      this.reason = event.reason;
      this.wasClean = event.wasClean;
    }
  };
  function isTerminalCloseEvent(event) {
    return event.code === 1008 || event.code >= 4e3 && event.code <= 4999;
  }
  function createStubProxy(call) {
    return new Proxy({}, { get: (_target, method) => {
      if (isInternalJsStubProp(method)) return;
      return (...args) => call(method, args);
    } });
  }
  var AgentClient = class extends PartySocket {
    /**
    * @deprecated Use agentFetch instead
    */
    static fetch(_opts) {
      throw new Error("AgentClient.fetch is not implemented, use agentFetch instead");
    }
    /**
    * Promise that resolves when identity has been received from the server.
    * Useful for waiting before making calls that depend on knowing the instance.
    * Resets on connection close so it can be awaited again after reconnect.
    */
    get ready() {
      return this._readyPromise;
    }
    _resetReady() {
      this._readyPromise = new Promise((resolve) => {
        this._resolveReady = resolve;
      });
    }
    constructor(options) {
      const agentNamespace = camelCaseToKebabCase(options.agent);
      const shouldReconnectOnClose = options.shouldReconnectOnClose;
      const classifyReconnect = (event) => (shouldReconnectOnClose?.(event) ?? true) && !isTerminalCloseEvent(event);
      const socketOptions = options.basePath ? {
        basePath: options.basePath,
        path: options.path,
        ...options,
        shouldReconnectOnClose: classifyReconnect
      } : {
        party: agentNamespace,
        prefix: "agents",
        room: options.name || "default",
        path: options.path,
        ...options,
        shouldReconnectOnClose: classifyReconnect
      };
      super(socketOptions);
      this.state = void 0;
      this.identified = false;
      this.connectionError = null;
      this._pendingCalls = /* @__PURE__ */ new Map();
      this._previousName = null;
      this._previousAgent = null;
      this.agent = agentNamespace;
      this.name = options.name || "default";
      this.options = options;
      this._resetReady();
      this.addEventListener("message", (event) => {
        if (typeof event.data === "string") {
          let parsedMessage;
          try {
            parsedMessage = JSON.parse(event.data);
          } catch (_error) {
            return;
          }
          if (parsedMessage.type === "cf_agent_identity") {
            const oldName = this._previousName;
            const oldAgent = this._previousAgent;
            const newName = parsedMessage.name;
            const newAgent = parsedMessage.agent;
            this.identified = true;
            this._resolveReady();
            if (oldName !== null && oldAgent !== null && (oldName !== newName || oldAgent !== newAgent)) if (this.options.onIdentityChange) this.options.onIdentityChange(oldName, newName, oldAgent, newAgent);
            else {
              const agentChanged = oldAgent !== newAgent;
              const nameChanged = oldName !== newName;
              let changeDescription = "";
              if (agentChanged && nameChanged) changeDescription = `agent "${oldAgent}" \u2192 "${newAgent}", instance "${oldName}" \u2192 "${newName}"`;
              else if (agentChanged) changeDescription = `agent "${oldAgent}" \u2192 "${newAgent}"`;
              else changeDescription = `instance "${oldName}" \u2192 "${newName}"`;
              console.warn(`[agents] Identity changed on reconnect: ${changeDescription}. This can happen with server-side routing (e.g., basePath with getAgentByName) where the instance is determined by auth/session. Provide onIdentityChange callback to handle this explicitly, or ignore if this is expected for your routing pattern.`);
            }
            this._previousName = newName;
            this._previousAgent = newAgent;
            this.name = newName;
            this.agent = newAgent;
            this.options.onIdentity?.(newName, newAgent);
            return;
          }
          if (parsedMessage.type === "cf_agent_state") {
            this.state = parsedMessage.state;
            this.options.onStateUpdate?.(parsedMessage.state, "server");
            return;
          }
          if (parsedMessage.type === "cf_agent_state_error") {
            this.options.onStateUpdateError?.(parsedMessage.error);
            return;
          }
          if (parsedMessage.type === "rpc") {
            const response = parsedMessage;
            const pending = this._pendingCalls.get(response.id);
            if (!pending) {
              console.warn(`[AgentClient] Discarded an RPC response with no matching pending call (id "${response.id}"). The call likely timed out or was rejected when its connection closed before the response arrived.`);
              return;
            }
            if (!response.success) {
              pending.reject(new Error(response.error));
              this._pendingCalls.delete(response.id);
              pending.stream?.onError?.(response.error);
              return;
            }
            if ("done" in response) if (response.done) {
              pending.resolve(response.result);
              this._pendingCalls.delete(response.id);
              pending.stream?.onDone?.(response.result);
            } else pending.stream?.onChunk?.(response.result);
            else {
              pending.resolve(response.result);
              this._pendingCalls.delete(response.id);
            }
          }
        }
      });
      this.addEventListener("open", () => {
        this.connectionError = null;
        for (const pending of this._pendingCalls.values()) pending.transmitted = true;
      });
      this.addEventListener("close", (event) => {
        const terminalClose = isTerminalCloseEvent(event);
        this.identified = false;
        this._resetReady();
        if (this.shouldReconnect) this._rejectPendingCalls("Connection closed", { onlyTransmitted: true });
        else {
          this._rejectPendingCalls("Connection closed");
          if (terminalClose) {
            const error = new AgentConnectionError(event);
            this.connectionError = error;
            this.options.onConnectionError?.(error);
          }
        }
      });
      this.call = this._callImpl.bind(this);
      this.stub = createStubProxy((method, args) => this._callImpl(method, args));
    }
    /**
    * Reject pending RPC calls with the given reason.
    * With `onlyTransmitted`, calls still sitting in the send buffer are
    * kept pending (they'll be flushed on reconnect).
    */
    _rejectPendingCalls(reason, { onlyTransmitted = false } = {}) {
      const error = new Error(reason);
      for (const [id, pending] of this._pendingCalls) {
        if (onlyTransmitted && !pending.transmitted) continue;
        this._pendingCalls.delete(id);
        pending.reject(error);
        pending.stream?.onError?.(reason);
      }
    }
    setState(state) {
      this.send(JSON.stringify({
        state,
        type: "cf_agent_state"
      }));
      this.state = state;
      this.options.onStateUpdate?.(state, "client");
    }
    /**
    * Close the connection and immediately reject all pending RPC calls.
    * This provides immediate feedback on intentional close rather than
    * waiting for the WebSocket close handshake to complete.
    *
    * Note: Any calls made after `close()` will be rejected when the
    * underlying WebSocket close event fires.
    */
    close(code, reason) {
      this._rejectPendingCalls("Connection closed");
      super.close(code, reason);
    }
    /**
    * Call a method on the Agent.
    * When AgentT is provided, method names are inferred from the agent's methods.
    * Falls back to untyped string-based calls when AgentT is not provided.
    */
    async _callImpl(method, args = [], options) {
      if (this.connectionError && this.readyState === this.CLOSED) throw new Error("Connection closed");
      return new Promise((resolve, reject) => {
        const id = crypto.randomUUID();
        let timeoutId;
        const isLegacyFormat = options && ("onChunk" in options || "onDone" in options || "onError" in options);
        const streamOptions = isLegacyFormat ? options : options?.stream;
        const timeout = isLegacyFormat ? void 0 : options?.timeout;
        const effectiveTimeout = timeout !== void 0 ? timeout : streamOptions ? void 0 : this.options.defaultCallTimeout ?? 3e4;
        if (effectiveTimeout) timeoutId = setTimeout(() => {
          const pending = this._pendingCalls.get(id);
          this._pendingCalls.delete(id);
          const errorMessage = `RPC call to ${method} timed out after ${effectiveTimeout}ms`;
          pending?.stream?.onError?.(errorMessage);
          reject(new Error(errorMessage));
        }, effectiveTimeout);
        this._pendingCalls.set(id, {
          reject: (e) => {
            if (timeoutId) clearTimeout(timeoutId);
            reject(e);
          },
          resolve: (value) => {
            if (timeoutId) clearTimeout(timeoutId);
            resolve(value);
          },
          stream: streamOptions,
          transmitted: this.readyState === this.OPEN
        });
        const request = {
          args,
          id,
          method,
          type: "rpc"
        };
        this.send(JSON.stringify(request));
      });
    }
  };

  // widget/chat-widget.js
  var AGENT_HOSTS = {
    localhost: "localhost:5173",
    "127.0.0.1": "localhost:5173",
    "nanodocs.pages.dev": "nanodocs-agent.nanofab.workers.dev"
  };
  var AGENT_NAME = "chat-agent";
  var STORAGE_KEY = "nanodocs-chat-conversation";
  var ROOT_ID = "nanodocs-chat";
  var host = AGENT_HOSTS[window.location.hostname];
  if (host && !document.getElementById(ROOT_ID)) {
    initWidget(host);
  }
  function initWidget(workerHost) {
    const httpBase = (workerHost.startsWith("localhost:") || workerHost.startsWith("127.0.0.1:") ? "http://" : "https://") + workerHost;
    let conversationId = sessionStorage.getItem(STORAGE_KEY);
    if (!conversationId) {
      conversationId = crypto.randomUUID();
      sessionStorage.setItem(STORAGE_KEY, conversationId);
    }
    let messages = [];
    let streamingMsg = null;
    let streamingEl = null;
    let pending = false;
    let activity = "";
    let client = null;
    let historyLoaded = false;
    const root = document.createElement("div");
    root.id = ROOT_ID;
    root.innerHTML = `
    <button class="ndc-fab" type="button" aria-label="Ask NanoDocs" aria-expanded="false">
      <svg viewBox="0 0 24 24" width="24" height="24" aria-hidden="true"><path fill="currentColor" d="M12 3C6.5 3 2 6.9 2 11.7c0 2.6 1.3 4.9 3.4 6.5-.2 1-.8 2.5-1.9 3.4 1.9.1 3.9-.6 5.3-1.5.7-.2 1.5-.3 2.2-.3 5.5 0 10-3.9 10-8.7S17.5 3 12 3z"/></svg>
    </button>
    <section class="ndc-panel" role="dialog" aria-label="NanoDocs assistant" hidden>
      <header class="ndc-header">
        <span class="ndc-title">Ask NanoDocs</span>
        <button class="ndc-reset" type="button" title="New conversation">
          <svg viewBox="0 0 24 24" width="18" height="18" aria-hidden="true"><path fill="currentColor" d="M17.65 6.35A7.96 7.96 0 0 0 12 4a8 8 0 1 0 7.73 10h-2.08A6 6 0 1 1 12 6c1.66 0 3.14.69 4.22 1.78L13 11h7V4l-2.35 2.35z"/></svg>
        </button>
        <button class="ndc-close" type="button" aria-label="Close chat">
          <svg viewBox="0 0 24 24" width="18" height="18" aria-hidden="true"><path fill="currentColor" d="M19 6.41 17.59 5 12 10.59 6.41 5 5 6.41 10.59 12 5 17.59 6.41 19 12 13.41 17.59 19 19 17.59 13.41 12z"/></svg>
        </button>
      </header>
      <div class="ndc-messages" aria-live="polite"></div>
      <div class="ndc-status" hidden></div>
      <form class="ndc-form">
        <textarea rows="1" placeholder="Ask about tools, chemicals, policies\u2026" aria-label="Your question"></textarea>
        <button class="ndc-send" type="submit" aria-label="Send">
          <svg viewBox="0 0 24 24" width="20" height="20" aria-hidden="true"><path fill="currentColor" d="M2 21l21-9L2 3v7l15 2-15 2v7z"/></svg>
        </button>
      </form>
      <p class="ndc-footnote">Answers come from published NanoDocs pages. Verify against the SOP before lab work.</p>
    </section>`;
    document.body.appendChild(root);
    const fab = root.querySelector(".ndc-fab");
    const panel = root.querySelector(".ndc-panel");
    const messagesEl = root.querySelector(".ndc-messages");
    const statusEl = root.querySelector(".ndc-status");
    const form = root.querySelector(".ndc-form");
    const input = root.querySelector("textarea");
    const sendBtn = root.querySelector(".ndc-send");
    if (window.document$ && typeof window.document$.subscribe === "function") {
      window.document$.subscribe(() => {
        if (!document.body.contains(root)) {
          document.body.appendChild(root);
        }
      });
    }
    function escapeHtml(text) {
      return text.replace(/&/g, "&amp;").replace(/</g, "&lt;").replace(/>/g, "&gt;").replace(/"/g, "&quot;");
    }
    function cleanDocsUrl(raw) {
      try {
        const url = new URL(raw);
        if (url.hostname === "nanodocs.pages.dev" || url.hostname === window.location.hostname) {
          return url.pathname;
        }
        return url.origin + url.pathname;
      } catch {
        return null;
      }
    }
    function renderInline(text) {
      let html = escapeHtml(text);
      html = html.replace(/`([^`]+)`/g, "<code>$1</code>");
      html = html.replace(/\*\*([^*]+)\*\*/g, "<strong>$1</strong>");
      html = html.replace(
        /\[([^\]]+)\]\((https?:\/\/[^)\s]+)\)/g,
        (m, label, url) => {
          const href = cleanDocsUrl(url);
          return href ? `<a href="${href}">${label}</a>` : label;
        }
      );
      html = html.replace(/(?<!["'=(\]])(https?:\/\/[^\s<)]+)/g, (m, url) => {
        const href = cleanDocsUrl(url);
        return href ? `<a href="${href}">${href}</a>` : m;
      });
      return html;
    }
    function renderMarkdown(text) {
      const lines = text.split("\n");
      const out = [];
      let list = null;
      let fence = null;
      const closeList = () => {
        if (list) {
          out.push(list === "ul" ? "</ul>" : "</ol>");
          list = null;
        }
      };
      for (const line of lines) {
        if (fence !== null) {
          if (/^```/.test(line)) {
            out.push(`<pre><code>${escapeHtml(fence.join("\n"))}</code></pre>`);
            fence = null;
          } else {
            fence.push(line);
          }
          continue;
        }
        if (/^```/.test(line)) {
          closeList();
          fence = [];
          continue;
        }
        const heading = line.match(/^(#{1,6})\s+(.*)$/);
        const bullet = line.match(/^\s*[-*]\s+(.*)$/);
        const numbered = line.match(/^\s*\d+[.)]\s+(.*)$/);
        if (heading) {
          closeList();
          out.push(`<p class="ndc-h">${renderInline(heading[2])}</p>`);
        } else if (bullet || numbered) {
          const kind = bullet ? "ul" : "ol";
          if (list !== kind) {
            closeList();
            out.push(kind === "ul" ? "<ul>" : "<ol>");
            list = kind;
          }
          out.push(`<li>${renderInline((bullet || numbered)[1])}</li>`);
        } else if (line.trim() === "") {
          closeList();
        } else {
          closeList();
          out.push(`<p>${renderInline(line)}</p>`);
        }
      }
      closeList();
      if (fence !== null) {
        out.push(`<pre><code>${escapeHtml(fence.join("\n"))}</code></pre>`);
      }
      return out.join("");
    }
    function extractCitations(msg) {
      const urls = [];
      for (const part of msg.parts || []) {
        const isSearch = typeof part.type === "string" && part.type.startsWith("tool-");
        if (!isSearch || part.state !== "output-available") continue;
        const output = typeof part.output === "string" ? part.output : "";
        for (const match of output.matchAll(
          /^\[\d+\]\s+(https?:\/\/\S+)\s+\(score/gm
        )) {
          const href = cleanDocsUrl(match[1]);
          if (href && !urls.includes(href)) {
            urls.push(href);
          }
        }
      }
      return urls;
    }
    function citedInProse(msg) {
      const hrefs = /* @__PURE__ */ new Set();
      for (const match of messageText(msg).matchAll(/https?:\/\/[^\s<)\]]+/g)) {
        const href = cleanDocsUrl(match[0].replace(/[.,;:!?]+$/, ""));
        if (href) hrefs.add(href);
      }
      return hrefs;
    }
    function citationLabel(href) {
      const segments = href.split("/").filter((s) => s && !s.startsWith("http"));
      const leaf = segments.length ? segments[segments.length - 1] : "Home";
      const title = leaf.replace(/[-_]/g, " ").replace(/\b\w/g, (c) => c.toUpperCase());
      const trail = segments.slice(0, -1).join(" / ");
      return { title, trail };
    }
    function messageText(msg) {
      return (msg.parts || []).filter((p) => p.type === "text").map((p) => p.text).join("");
    }
    function isPinned() {
      return messagesEl.scrollHeight - messagesEl.scrollTop - messagesEl.clientHeight < 40;
    }
    function scrollToBottom() {
      messagesEl.scrollTop = messagesEl.scrollHeight;
    }
    function assistantBody(msg) {
      const text = messageText(msg);
      return msg === streamingMsg && text === "" ? `<span class="ndc-dots"><i></i><i></i><i></i></span>${activity ? `<span class="ndc-activity">${escapeHtml(activity)}</span>` : ""}` : renderMarkdown(text);
    }
    function render(forcePin = false) {
      const pinned = forcePin || isPinned();
      const items = [];
      for (const msg of messages) {
        if (msg.role === "user") {
          items.push(
            `<div class="ndc-msg ndc-user">${escapeHtml(messageText(msg))}</div>`
          );
        } else if (msg.role === "assistant") {
          let cardHrefs = [];
          if (msg !== streamingMsg) {
            const retrieved = extractCitations(msg);
            const used = citedInProse(msg);
            const cited = retrieved.filter((href) => used.has(href));
            cardHrefs = cited.length ? cited : retrieved;
          }
          const cards = cardHrefs.map((href) => {
            const { title, trail } = citationLabel(href);
            return `<a class="ndc-cite" href="${href}">
              <span class="ndc-cite-title">${escapeHtml(title)}</span>
              ${trail ? `<span class="ndc-cite-trail">${escapeHtml(trail)}</span>` : ""}
            </a>`;
          }).join("");
          items.push(
            `<div class="ndc-msg ndc-assistant">${assistantBody(msg)}${cards ? `<div class="ndc-cites" aria-label="Sources">${cards}</div>` : ""}</div>`
          );
        }
      }
      if (!items.length) {
        items.push(
          `<div class="ndc-empty">Ask about any published SOP, chemical procedure, or lab policy.</div>`
        );
      }
      messagesEl.innerHTML = items.join("");
      streamingEl = streamingMsg && messagesEl.lastElementChild?.classList.contains("ndc-assistant") ? messagesEl.lastElementChild : null;
      if (pinned) {
        scrollToBottom();
      }
      sendBtn.disabled = pending;
    }
    function updateStreaming() {
      if (!streamingMsg) return;
      if (!streamingEl || !messagesEl.contains(streamingEl)) {
        render();
        return;
      }
      const pinned = isPinned();
      streamingEl.innerHTML = assistantBody(streamingMsg);
      if (pinned) {
        scrollToBottom();
      }
    }
    function setStatus(text) {
      statusEl.textContent = text || "";
      statusEl.hidden = !text;
    }
    function ensureClient() {
      if (client) return client;
      client = new AgentClient({
        host: workerHost,
        agent: AGENT_NAME,
        name: conversationId
      });
      client.addEventListener("open", () => {
        setStatus("");
        if (pending) {
          client.send(JSON.stringify({ type: "cf_agent_stream_resume_request" }));
        }
      });
      client.addEventListener("close", () => {
        if (pending) {
          setStatus("Connection lost \u2014 reconnecting\u2026");
        }
      });
      client.addEventListener("error", () => {
        setStatus("Assistant unreachable \u2014 retrying\u2026");
      });
      client.addEventListener("message", (event) => {
        if (typeof event.data !== "string") return;
        let frame;
        try {
          frame = JSON.parse(event.data);
        } catch {
          return;
        }
        handleFrame(frame);
      });
      return client;
    }
    function beginAssistantMessage() {
      streamingMsg = { id: crypto.randomUUID(), role: "assistant", parts: [] };
      messages.push(streamingMsg);
      return streamingMsg;
    }
    function applyChunk(chunk) {
      const msg = streamingMsg || beginAssistantMessage();
      switch (chunk.type) {
        // The model reasons before every step, and there are quiet gaps
        // between steps — cover both so the visitor never stares at
        // silent dots wondering if the bot hung.
        case "start-step":
        case "reasoning-start":
          activity = "Thinking\u2026";
          break;
        case "text-start":
          activity = "";
          msg.parts.push({ type: "text", text: "", _sid: chunk.id });
          break;
        case "text-delta": {
          let part = msg.parts.findLast(
            (p) => p.type === "text" && p._sid === chunk.id
          );
          if (!part) {
            part = { type: "text", text: "", _sid: chunk.id };
            msg.parts.push(part);
          }
          part.text += chunk.delta || "";
          break;
        }
        // Tool parts must stay schema-valid (toolCallId + input + output):
        // this whole list is sent back to the Agent on the next turn, and
        // convertToModelMessages rejects incomplete tool parts.
        case "tool-input-start":
          activity = "Searching the docs\u2026";
          break;
        case "tool-input-available": {
          const query = chunk.input && typeof chunk.input.query === "string" ? chunk.input.query : "";
          activity = query ? `Searching: ${query}` : "Searching the docs\u2026";
          msg.parts.push({
            type: `tool-${chunk.toolName || "searchDocs"}`,
            toolCallId: chunk.toolCallId,
            state: "input-available",
            input: chunk.input
          });
          break;
        }
        case "tool-output-available": {
          const part = msg.parts.find(
            (p) => p.toolCallId && p.toolCallId === chunk.toolCallId
          );
          if (part) {
            part.state = "output-available";
            part.output = chunk.output;
          }
          activity = "Thinking\u2026";
          break;
        }
        case "error": {
          const err = chunk.errorText || "Something went wrong \u2014 try again.";
          setStatus(err);
          if (!messageText(msg)) {
            msg.parts.push({ type: "text", text: err });
          }
          break;
        }
        default:
          break;
      }
      updateStreaming();
    }
    function finishTurn(keepStatus) {
      pending = false;
      streamingMsg = null;
      activity = "";
      if (!keepStatus) {
        setStatus("");
      }
      render();
      const localLen = messages.length;
      setTimeout(async () => {
        if (pending) return;
        try {
          const res = await fetch(
            `${httpBase}/agents/${AGENT_NAME}/${conversationId}/get-messages`
          );
          if (!res.ok) return;
          const server = await res.json();
          if (!pending && Array.isArray(server) && server.length >= localLen) {
            messages = server;
            render();
          }
        } catch {
        }
      }, 600);
    }
    function handleFrame(frame) {
      switch (frame.type) {
        case "cf_agent_chat_messages":
          if (!pending) {
            messages = frame.messages || [];
            render();
          }
          break;
        case "cf_agent_use_chat_response":
          if (frame.error) {
            const err = typeof frame.body === "string" && frame.body ? frame.body : "Something went wrong \u2014 try again.";
            const msg = streamingMsg || beginAssistantMessage();
            if (!messageText(msg)) {
              msg.parts.push({ type: "text", text: err });
            }
            finishTurn(true);
            setStatus(err);
            break;
          }
          if (frame.body) {
            let chunk;
            try {
              chunk = JSON.parse(frame.body);
            } catch {
              chunk = null;
            }
            if (chunk) applyChunk(chunk);
          }
          if (frame.done) {
            finishTurn();
          }
          break;
        case "cf_agent_stream_resuming":
          pending = true;
          streamingMsg = null;
          activity = "Thinking\u2026";
          client.send(
            JSON.stringify({ type: "cf_agent_stream_resume_ack", id: frame.id })
          );
          break;
        case "cf_agent_message_updated": {
          const idx = messages.findIndex((m) => m.id === frame.message?.id);
          if (idx >= 0) {
            messages[idx] = frame.message;
            render();
          }
          break;
        }
        default:
          break;
      }
    }
    async function loadHistory() {
      if (historyLoaded) return;
      try {
        const res = await fetch(
          `${httpBase}/agents/${AGENT_NAME}/${conversationId}/get-messages`
        );
        if (!res.ok) throw new Error(`HTTP ${res.status}`);
        const server = await res.json();
        historyLoaded = true;
        if (Array.isArray(server) && server.length > messages.length) {
          messages = server;
        }
        setStatus("");
        render();
      } catch {
        setStatus("Assistant unreachable \u2014 is it offline?");
      }
    }
    function sendQuestion(text) {
      const socket = ensureClient();
      if (socket.readyState !== 1) {
        setStatus("Connecting\u2026");
      }
      activity = "Thinking\u2026";
      messages.push({
        id: crypto.randomUUID(),
        role: "user",
        parts: [{ type: "text", text }]
      });
      pending = true;
      streamingMsg = null;
      socket.send(
        JSON.stringify({
          type: "cf_agent_use_chat_request",
          id: crypto.randomUUID(),
          init: {
            method: "POST",
            body: JSON.stringify({
              messages,
              // Hint only — the Worker's system prompt keeps search corpus-wide.
              page: window.location.origin + window.location.pathname
            })
          }
        })
      );
      render(true);
    }
    function newConversation() {
      conversationId = crypto.randomUUID();
      sessionStorage.setItem(STORAGE_KEY, conversationId);
      if (client) {
        client.close();
        client = null;
      }
      messages = [];
      streamingMsg = null;
      streamingEl = null;
      pending = false;
      historyLoaded = true;
      setStatus("");
      render();
      ensureClient();
    }
    function openPanel() {
      panel.hidden = false;
      fab.setAttribute("aria-expanded", "true");
      root.classList.add("ndc-open");
      ensureClient();
      loadHistory();
      render(true);
      input.focus();
    }
    function closePanel() {
      panel.hidden = true;
      fab.setAttribute("aria-expanded", "false");
      root.classList.remove("ndc-open");
    }
    fab.addEventListener("click", () => {
      if (panel.hidden) openPanel();
      else closePanel();
    });
    root.querySelector(".ndc-close").addEventListener("click", closePanel);
    root.querySelector(".ndc-reset").addEventListener("click", newConversation);
    document.addEventListener("keydown", (e) => {
      if (e.key === "Escape" && !panel.hidden) closePanel();
    });
    form.addEventListener("submit", (e) => {
      e.preventDefault();
      const text = input.value.trim();
      if (!text || pending) return;
      sendQuestion(text);
      input.value = "";
      input.style.height = "";
    });
    input.addEventListener("keydown", (e) => {
      if (e.key === "Enter" && !e.shiftKey) {
        e.preventDefault();
        form.requestSubmit();
      }
    });
    input.addEventListener("input", () => {
      input.style.height = "";
      input.style.height = `${Math.min(input.scrollHeight, 120)}px`;
    });
  }
})();
